with-expecter: true
resolve-type-alias: false
disable-version-string: true
issue-845-fix: true
filename: "mock_{{.InterfaceName}}.go"
dir: "{{.InterfaceDir}}/mocks"
mockname: "Mock{{.InterfaceName}}"
outpkg: mocks
packages:
  github.com/dias-web/lms-system/internal/repository:
    interfaces:
      CourseRepository:
      ChapterRepository:
      LessonRepository:
  github.com/dias-web/lms-system/internal/service:
    interfaces:
      CourseService:
      ChapterService:
      LessonService:
      AuthService:
      KeycloakClient:
