// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/dias-web/lms-system/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// MockAttachmentRepository is an autogenerated mock type for the AttachmentRepository type
type MockAttachmentRepository struct {
	mock.Mock
}

type MockAttachmentRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAttachmentRepository) EXPECT() *MockAttachmentRepository_Expecter {
	return &MockAttachmentRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, a
func (_m *MockAttachmentRepository) Create(ctx context.Context, a *entity.Attachment) error {
	ret := _m.Called(ctx, a)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Attachment) error); ok {
		r0 = rf(ctx, a)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAttachmentRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockAttachmentRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - a *entity.Attachment
func (_e *MockAttachmentRepository_Expecter) Create(ctx interface{}, a interface{}) *MockAttachmentRepository_Create_Call {
	return &MockAttachmentRepository_Create_Call{Call: _e.mock.On("Create", ctx, a)}
}

func (_c *MockAttachmentRepository_Create_Call) Run(run func(ctx context.Context, a *entity.Attachment)) *MockAttachmentRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Attachment))
	})
	return _c
}

func (_c *MockAttachmentRepository_Create_Call) Return(_a0 error) *MockAttachmentRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAttachmentRepository_Create_Call) RunAndReturn(run func(context.Context, *entity.Attachment) error) *MockAttachmentRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockAttachmentRepository) Delete(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAttachmentRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockAttachmentRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockAttachmentRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockAttachmentRepository_Delete_Call {
	return &MockAttachmentRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockAttachmentRepository_Delete_Call) Run(run func(ctx context.Context, id uint)) *MockAttachmentRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockAttachmentRepository_Delete_Call) Return(_a0 error) *MockAttachmentRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAttachmentRepository_Delete_Call) RunAndReturn(run func(context.Context, uint) error) *MockAttachmentRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockAttachmentRepository) GetByID(ctx context.Context, id uint) (*entity.Attachment, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.Attachment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*entity.Attachment, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *entity.Attachment); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Attachment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAttachmentRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockAttachmentRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockAttachmentRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockAttachmentRepository_GetByID_Call {
	return &MockAttachmentRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockAttachmentRepository_GetByID_Call) Run(run func(ctx context.Context, id uint)) *MockAttachmentRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockAttachmentRepository_GetByID_Call) Return(_a0 *entity.Attachment, _a1 error) *MockAttachmentRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAttachmentRepository_GetByID_Call) RunAndReturn(run func(context.Context, uint) (*entity.Attachment, error)) *MockAttachmentRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByLesson provides a mock function with given fields: ctx, lessonID
func (_m *MockAttachmentRepository) ListByLesson(ctx context.Context, lessonID uint) ([]entity.Attachment, error) {
	ret := _m.Called(ctx, lessonID)

	if len(ret) == 0 {
		panic("no return value specified for ListByLesson")
	}

	var r0 []entity.Attachment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]entity.Attachment, error)); ok {
		return rf(ctx, lessonID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []entity.Attachment); ok {
		r0 = rf(ctx, lessonID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Attachment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, lessonID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAttachmentRepository_ListByLesson_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByLesson'
type MockAttachmentRepository_ListByLesson_Call struct {
	*mock.Call
}

// ListByLesson is a helper method to define mock.On call
//   - ctx context.Context
//   - lessonID uint
func (_e *MockAttachmentRepository_Expecter) ListByLesson(ctx interface{}, lessonID interface{}) *MockAttachmentRepository_ListByLesson_Call {
	return &MockAttachmentRepository_ListByLesson_Call{Call: _e.mock.On("ListByLesson", ctx, lessonID)}
}

func (_c *MockAttachmentRepository_ListByLesson_Call) Run(run func(ctx context.Context, lessonID uint)) *MockAttachmentRepository_ListByLesson_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockAttachmentRepository_ListByLesson_Call) Return(_a0 []entity.Attachment, _a1 error) *MockAttachmentRepository_ListByLesson_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAttachmentRepository_ListByLesson_Call) RunAndReturn(run func(context.Context, uint) ([]entity.Attachment, error)) *MockAttachmentRepository_ListByLesson_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAttachmentRepository creates a new instance of MockAttachmentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAttachmentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAttachmentRepository {
	mock := &MockAttachmentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
