// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/dias-web/lms-system/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// MockChapterRepository is an autogenerated mock type for the ChapterRepository type
type MockChapterRepository struct {
	mock.Mock
}

type MockChapterRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChapterRepository) EXPECT() *MockChapterRepository_Expecter {
	return &MockChapterRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, chapter
func (_m *MockChapterRepository) Create(ctx context.Context, chapter *entity.Chapter) error {
	ret := _m.Called(ctx, chapter)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Chapter) error); ok {
		r0 = rf(ctx, chapter)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockChapterRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockChapterRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - chapter *entity.Chapter
func (_e *MockChapterRepository_Expecter) Create(ctx interface{}, chapter interface{}) *MockChapterRepository_Create_Call {
	return &MockChapterRepository_Create_Call{Call: _e.mock.On("Create", ctx, chapter)}
}

func (_c *MockChapterRepository_Create_Call) Run(run func(ctx context.Context, chapter *entity.Chapter)) *MockChapterRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Chapter))
	})
	return _c
}

func (_c *MockChapterRepository_Create_Call) Return(_a0 error) *MockChapterRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChapterRepository_Create_Call) RunAndReturn(run func(context.Context, *entity.Chapter) error) *MockChapterRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockChapterRepository) Delete(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockChapterRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockChapterRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockChapterRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockChapterRepository_Delete_Call {
	return &MockChapterRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockChapterRepository_Delete_Call) Run(run func(ctx context.Context, id uint)) *MockChapterRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockChapterRepository_Delete_Call) Return(_a0 error) *MockChapterRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChapterRepository_Delete_Call) RunAndReturn(run func(context.Context, uint) error) *MockChapterRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockChapterRepository) GetByID(ctx context.Context, id uint) (*entity.Chapter, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.Chapter
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*entity.Chapter, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *entity.Chapter); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Chapter)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockChapterRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockChapterRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockChapterRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockChapterRepository_GetByID_Call {
	return &MockChapterRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockChapterRepository_GetByID_Call) Run(run func(ctx context.Context, id uint)) *MockChapterRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockChapterRepository_GetByID_Call) Return(_a0 *entity.Chapter, _a1 error) *MockChapterRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockChapterRepository_GetByID_Call) RunAndReturn(run func(context.Context, uint) (*entity.Chapter, error)) *MockChapterRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByIDWithLessons provides a mock function with given fields: ctx, id
func (_m *MockChapterRepository) GetByIDWithLessons(ctx context.Context, id uint) (*entity.Chapter, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByIDWithLessons")
	}

	var r0 *entity.Chapter
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*entity.Chapter, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *entity.Chapter); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Chapter)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockChapterRepository_GetByIDWithLessons_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByIDWithLessons'
type MockChapterRepository_GetByIDWithLessons_Call struct {
	*mock.Call
}

// GetByIDWithLessons is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockChapterRepository_Expecter) GetByIDWithLessons(ctx interface{}, id interface{}) *MockChapterRepository_GetByIDWithLessons_Call {
	return &MockChapterRepository_GetByIDWithLessons_Call{Call: _e.mock.On("GetByIDWithLessons", ctx, id)}
}

func (_c *MockChapterRepository_GetByIDWithLessons_Call) Run(run func(ctx context.Context, id uint)) *MockChapterRepository_GetByIDWithLessons_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockChapterRepository_GetByIDWithLessons_Call) Return(_a0 *entity.Chapter, _a1 error) *MockChapterRepository_GetByIDWithLessons_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockChapterRepository_GetByIDWithLessons_Call) RunAndReturn(run func(context.Context, uint) (*entity.Chapter, error)) *MockChapterRepository_GetByIDWithLessons_Call {
	_c.Call.Return(run)
	return _c
}

// ListByCourse provides a mock function with given fields: ctx, courseID
func (_m *MockChapterRepository) ListByCourse(ctx context.Context, courseID uint) ([]entity.Chapter, error) {
	ret := _m.Called(ctx, courseID)

	if len(ret) == 0 {
		panic("no return value specified for ListByCourse")
	}

	var r0 []entity.Chapter
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]entity.Chapter, error)); ok {
		return rf(ctx, courseID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []entity.Chapter); ok {
		r0 = rf(ctx, courseID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Chapter)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, courseID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockChapterRepository_ListByCourse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByCourse'
type MockChapterRepository_ListByCourse_Call struct {
	*mock.Call
}

// ListByCourse is a helper method to define mock.On call
//   - ctx context.Context
//   - courseID uint
func (_e *MockChapterRepository_Expecter) ListByCourse(ctx interface{}, courseID interface{}) *MockChapterRepository_ListByCourse_Call {
	return &MockChapterRepository_ListByCourse_Call{Call: _e.mock.On("ListByCourse", ctx, courseID)}
}

func (_c *MockChapterRepository_ListByCourse_Call) Run(run func(ctx context.Context, courseID uint)) *MockChapterRepository_ListByCourse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockChapterRepository_ListByCourse_Call) Return(_a0 []entity.Chapter, _a1 error) *MockChapterRepository_ListByCourse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockChapterRepository_ListByCourse_Call) RunAndReturn(run func(context.Context, uint) ([]entity.Chapter, error)) *MockChapterRepository_ListByCourse_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, chapter
func (_m *MockChapterRepository) Update(ctx context.Context, chapter *entity.Chapter) error {
	ret := _m.Called(ctx, chapter)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Chapter) error); ok {
		r0 = rf(ctx, chapter)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockChapterRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockChapterRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - chapter *entity.Chapter
func (_e *MockChapterRepository_Expecter) Update(ctx interface{}, chapter interface{}) *MockChapterRepository_Update_Call {
	return &MockChapterRepository_Update_Call{Call: _e.mock.On("Update", ctx, chapter)}
}

func (_c *MockChapterRepository_Update_Call) Run(run func(ctx context.Context, chapter *entity.Chapter)) *MockChapterRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Chapter))
	})
	return _c
}

func (_c *MockChapterRepository_Update_Call) Return(_a0 error) *MockChapterRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChapterRepository_Update_Call) RunAndReturn(run func(context.Context, *entity.Chapter) error) *MockChapterRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockChapterRepository creates a new instance of MockChapterRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChapterRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChapterRepository {
	mock := &MockChapterRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
