// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/dias-web/lms-system/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// MockCourseRepository is an autogenerated mock type for the CourseRepository type
type MockCourseRepository struct {
	mock.Mock
}

type MockCourseRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCourseRepository) EXPECT() *MockCourseRepository_Expecter {
	return &MockCourseRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, course
func (_m *MockCourseRepository) Create(ctx context.Context, course *entity.Course) error {
	ret := _m.Called(ctx, course)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Course) error); ok {
		r0 = rf(ctx, course)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCourseRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockCourseRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - course *entity.Course
func (_e *MockCourseRepository_Expecter) Create(ctx interface{}, course interface{}) *MockCourseRepository_Create_Call {
	return &MockCourseRepository_Create_Call{Call: _e.mock.On("Create", ctx, course)}
}

func (_c *MockCourseRepository_Create_Call) Run(run func(ctx context.Context, course *entity.Course)) *MockCourseRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Course))
	})
	return _c
}

func (_c *MockCourseRepository_Create_Call) Return(_a0 error) *MockCourseRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCourseRepository_Create_Call) RunAndReturn(run func(context.Context, *entity.Course) error) *MockCourseRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockCourseRepository) Delete(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCourseRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockCourseRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockCourseRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockCourseRepository_Delete_Call {
	return &MockCourseRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockCourseRepository_Delete_Call) Run(run func(ctx context.Context, id uint)) *MockCourseRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockCourseRepository_Delete_Call) Return(_a0 error) *MockCourseRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCourseRepository_Delete_Call) RunAndReturn(run func(context.Context, uint) error) *MockCourseRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockCourseRepository) GetByID(ctx context.Context, id uint) (*entity.Course, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.Course
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*entity.Course, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *entity.Course); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Course)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCourseRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockCourseRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockCourseRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockCourseRepository_GetByID_Call {
	return &MockCourseRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockCourseRepository_GetByID_Call) Run(run func(ctx context.Context, id uint)) *MockCourseRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockCourseRepository_GetByID_Call) Return(_a0 *entity.Course, _a1 error) *MockCourseRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCourseRepository_GetByID_Call) RunAndReturn(run func(context.Context, uint) (*entity.Course, error)) *MockCourseRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByIDWithChapters provides a mock function with given fields: ctx, id
func (_m *MockCourseRepository) GetByIDWithChapters(ctx context.Context, id uint) (*entity.Course, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByIDWithChapters")
	}

	var r0 *entity.Course
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*entity.Course, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *entity.Course); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Course)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCourseRepository_GetByIDWithChapters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByIDWithChapters'
type MockCourseRepository_GetByIDWithChapters_Call struct {
	*mock.Call
}

// GetByIDWithChapters is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockCourseRepository_Expecter) GetByIDWithChapters(ctx interface{}, id interface{}) *MockCourseRepository_GetByIDWithChapters_Call {
	return &MockCourseRepository_GetByIDWithChapters_Call{Call: _e.mock.On("GetByIDWithChapters", ctx, id)}
}

func (_c *MockCourseRepository_GetByIDWithChapters_Call) Run(run func(ctx context.Context, id uint)) *MockCourseRepository_GetByIDWithChapters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockCourseRepository_GetByIDWithChapters_Call) Return(_a0 *entity.Course, _a1 error) *MockCourseRepository_GetByIDWithChapters_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCourseRepository_GetByIDWithChapters_Call) RunAndReturn(run func(context.Context, uint) (*entity.Course, error)) *MockCourseRepository_GetByIDWithChapters_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx
func (_m *MockCourseRepository) List(ctx context.Context) ([]entity.Course, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []entity.Course
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]entity.Course, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []entity.Course); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Course)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCourseRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockCourseRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockCourseRepository_Expecter) List(ctx interface{}) *MockCourseRepository_List_Call {
	return &MockCourseRepository_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockCourseRepository_List_Call) Run(run func(ctx context.Context)) *MockCourseRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockCourseRepository_List_Call) Return(_a0 []entity.Course, _a1 error) *MockCourseRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCourseRepository_List_Call) RunAndReturn(run func(context.Context) ([]entity.Course, error)) *MockCourseRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, course
func (_m *MockCourseRepository) Update(ctx context.Context, course *entity.Course) error {
	ret := _m.Called(ctx, course)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Course) error); ok {
		r0 = rf(ctx, course)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCourseRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockCourseRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - course *entity.Course
func (_e *MockCourseRepository_Expecter) Update(ctx interface{}, course interface{}) *MockCourseRepository_Update_Call {
	return &MockCourseRepository_Update_Call{Call: _e.mock.On("Update", ctx, course)}
}

func (_c *MockCourseRepository_Update_Call) Run(run func(ctx context.Context, course *entity.Course)) *MockCourseRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Course))
	})
	return _c
}

func (_c *MockCourseRepository_Update_Call) Return(_a0 error) *MockCourseRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCourseRepository_Update_Call) RunAndReturn(run func(context.Context, *entity.Course) error) *MockCourseRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCourseRepository creates a new instance of MockCourseRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCourseRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCourseRepository {
	mock := &MockCourseRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
