// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/dias-web/lms-system/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// MockLessonRepository is an autogenerated mock type for the LessonRepository type
type MockLessonRepository struct {
	mock.Mock
}

type MockLessonRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLessonRepository) EXPECT() *MockLessonRepository_Expecter {
	return &MockLessonRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, lesson
func (_m *MockLessonRepository) Create(ctx context.Context, lesson *entity.Lesson) error {
	ret := _m.Called(ctx, lesson)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Lesson) error); ok {
		r0 = rf(ctx, lesson)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLessonRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockLessonRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - lesson *entity.Lesson
func (_e *MockLessonRepository_Expecter) Create(ctx interface{}, lesson interface{}) *MockLessonRepository_Create_Call {
	return &MockLessonRepository_Create_Call{Call: _e.mock.On("Create", ctx, lesson)}
}

func (_c *MockLessonRepository_Create_Call) Run(run func(ctx context.Context, lesson *entity.Lesson)) *MockLessonRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Lesson))
	})
	return _c
}

func (_c *MockLessonRepository_Create_Call) Return(_a0 error) *MockLessonRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLessonRepository_Create_Call) RunAndReturn(run func(context.Context, *entity.Lesson) error) *MockLessonRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockLessonRepository) Delete(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLessonRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockLessonRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockLessonRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockLessonRepository_Delete_Call {
	return &MockLessonRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockLessonRepository_Delete_Call) Run(run func(ctx context.Context, id uint)) *MockLessonRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockLessonRepository_Delete_Call) Return(_a0 error) *MockLessonRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLessonRepository_Delete_Call) RunAndReturn(run func(context.Context, uint) error) *MockLessonRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockLessonRepository) GetByID(ctx context.Context, id uint) (*entity.Lesson, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.Lesson
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*entity.Lesson, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *entity.Lesson); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Lesson)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLessonRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockLessonRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockLessonRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockLessonRepository_GetByID_Call {
	return &MockLessonRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockLessonRepository_GetByID_Call) Run(run func(ctx context.Context, id uint)) *MockLessonRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockLessonRepository_GetByID_Call) Return(_a0 *entity.Lesson, _a1 error) *MockLessonRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLessonRepository_GetByID_Call) RunAndReturn(run func(context.Context, uint) (*entity.Lesson, error)) *MockLessonRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByChapter provides a mock function with given fields: ctx, chapterID
func (_m *MockLessonRepository) ListByChapter(ctx context.Context, chapterID uint) ([]entity.Lesson, error) {
	ret := _m.Called(ctx, chapterID)

	if len(ret) == 0 {
		panic("no return value specified for ListByChapter")
	}

	var r0 []entity.Lesson
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]entity.Lesson, error)); ok {
		return rf(ctx, chapterID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []entity.Lesson); ok {
		r0 = rf(ctx, chapterID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Lesson)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, chapterID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLessonRepository_ListByChapter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByChapter'
type MockLessonRepository_ListByChapter_Call struct {
	*mock.Call
}

// ListByChapter is a helper method to define mock.On call
//   - ctx context.Context
//   - chapterID uint
func (_e *MockLessonRepository_Expecter) ListByChapter(ctx interface{}, chapterID interface{}) *MockLessonRepository_ListByChapter_Call {
	return &MockLessonRepository_ListByChapter_Call{Call: _e.mock.On("ListByChapter", ctx, chapterID)}
}

func (_c *MockLessonRepository_ListByChapter_Call) Run(run func(ctx context.Context, chapterID uint)) *MockLessonRepository_ListByChapter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockLessonRepository_ListByChapter_Call) Return(_a0 []entity.Lesson, _a1 error) *MockLessonRepository_ListByChapter_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLessonRepository_ListByChapter_Call) RunAndReturn(run func(context.Context, uint) ([]entity.Lesson, error)) *MockLessonRepository_ListByChapter_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, lesson
func (_m *MockLessonRepository) Update(ctx context.Context, lesson *entity.Lesson) error {
	ret := _m.Called(ctx, lesson)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Lesson) error); ok {
		r0 = rf(ctx, lesson)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLessonRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockLessonRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - lesson *entity.Lesson
func (_e *MockLessonRepository_Expecter) Update(ctx interface{}, lesson interface{}) *MockLessonRepository_Update_Call {
	return &MockLessonRepository_Update_Call{Call: _e.mock.On("Update", ctx, lesson)}
}

func (_c *MockLessonRepository_Update_Call) Run(run func(ctx context.Context, lesson *entity.Lesson)) *MockLessonRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Lesson))
	})
	return _c
}

func (_c *MockLessonRepository_Update_Call) Return(_a0 error) *MockLessonRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLessonRepository_Update_Call) RunAndReturn(run func(context.Context, *entity.Lesson) error) *MockLessonRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLessonRepository creates a new instance of MockLessonRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLessonRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLessonRepository {
	mock := &MockLessonRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
