// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	keycloak "github.com/dias-web/lms-system/internal/keycloak"
	mock "github.com/stretchr/testify/mock"
)

// MockKeycloakClient is an autogenerated mock type for the KeycloakClient type
type MockKeycloakClient struct {
	mock.Mock
}

type MockKeycloakClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockKeycloakClient) EXPECT() *MockKeycloakClient_Expecter {
	return &MockKeycloakClient_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function with given fields: ctx, in
func (_m *MockKeycloakClient) CreateUser(ctx context.Context, in keycloak.CreateUserInput) (string, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, keycloak.CreateUserInput) (string, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, keycloak.CreateUserInput) string); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, keycloak.CreateUserInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKeycloakClient_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockKeycloakClient_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - in keycloak.CreateUserInput
func (_e *MockKeycloakClient_Expecter) CreateUser(ctx interface{}, in interface{}) *MockKeycloakClient_CreateUser_Call {
	return &MockKeycloakClient_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, in)}
}

func (_c *MockKeycloakClient_CreateUser_Call) Run(run func(ctx context.Context, in keycloak.CreateUserInput)) *MockKeycloakClient_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(keycloak.CreateUserInput))
	})
	return _c
}

func (_c *MockKeycloakClient_CreateUser_Call) Return(_a0 string, _a1 error) *MockKeycloakClient_CreateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKeycloakClient_CreateUser_Call) RunAndReturn(run func(context.Context, keycloak.CreateUserInput) (string, error)) *MockKeycloakClient_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function with given fields: ctx, username, password
func (_m *MockKeycloakClient) Login(ctx context.Context, username string, password string) (*keycloak.Token, error) {
	ret := _m.Called(ctx, username, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *keycloak.Token
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*keycloak.Token, error)); ok {
		return rf(ctx, username, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *keycloak.Token); ok {
		r0 = rf(ctx, username, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*keycloak.Token)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, username, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKeycloakClient_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockKeycloakClient_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - password string
func (_e *MockKeycloakClient_Expecter) Login(ctx interface{}, username interface{}, password interface{}) *MockKeycloakClient_Login_Call {
	return &MockKeycloakClient_Login_Call{Call: _e.mock.On("Login", ctx, username, password)}
}

func (_c *MockKeycloakClient_Login_Call) Run(run func(ctx context.Context, username string, password string)) *MockKeycloakClient_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockKeycloakClient_Login_Call) Return(_a0 *keycloak.Token, _a1 error) *MockKeycloakClient_Login_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKeycloakClient_Login_Call) RunAndReturn(run func(context.Context, string, string) (*keycloak.Token, error)) *MockKeycloakClient_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Refresh provides a mock function with given fields: ctx, refreshToken
func (_m *MockKeycloakClient) Refresh(ctx context.Context, refreshToken string) (*keycloak.Token, error) {
	ret := _m.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for Refresh")
	}

	var r0 *keycloak.Token
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*keycloak.Token, error)); ok {
		return rf(ctx, refreshToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *keycloak.Token); ok {
		r0 = rf(ctx, refreshToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*keycloak.Token)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, refreshToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKeycloakClient_Refresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Refresh'
type MockKeycloakClient_Refresh_Call struct {
	*mock.Call
}

// Refresh is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
func (_e *MockKeycloakClient_Expecter) Refresh(ctx interface{}, refreshToken interface{}) *MockKeycloakClient_Refresh_Call {
	return &MockKeycloakClient_Refresh_Call{Call: _e.mock.On("Refresh", ctx, refreshToken)}
}

func (_c *MockKeycloakClient_Refresh_Call) Run(run func(ctx context.Context, refreshToken string)) *MockKeycloakClient_Refresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockKeycloakClient_Refresh_Call) Return(_a0 *keycloak.Token, _a1 error) *MockKeycloakClient_Refresh_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKeycloakClient_Refresh_Call) RunAndReturn(run func(context.Context, string) (*keycloak.Token, error)) *MockKeycloakClient_Refresh_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockKeycloakClient creates a new instance of MockKeycloakClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKeycloakClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKeycloakClient {
	mock := &MockKeycloakClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
