// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/dias-web/lms-system/internal/dto"
	mock "github.com/stretchr/testify/mock"
)

// MockCourseService is an autogenerated mock type for the CourseService type
type MockCourseService struct {
	mock.Mock
}

type MockCourseService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCourseService) EXPECT() *MockCourseService_Expecter {
	return &MockCourseService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, req
func (_m *MockCourseService) Create(ctx context.Context, req dto.CreateCourseRequest) (dto.CourseResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 dto.CourseResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateCourseRequest) (dto.CourseResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateCourseRequest) dto.CourseResponse); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(dto.CourseResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.CreateCourseRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCourseService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockCourseService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - req dto.CreateCourseRequest
func (_e *MockCourseService_Expecter) Create(ctx interface{}, req interface{}) *MockCourseService_Create_Call {
	return &MockCourseService_Create_Call{Call: _e.mock.On("Create", ctx, req)}
}

func (_c *MockCourseService_Create_Call) Run(run func(ctx context.Context, req dto.CreateCourseRequest)) *MockCourseService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dto.CreateCourseRequest))
	})
	return _c
}

func (_c *MockCourseService_Create_Call) Return(_a0 dto.CourseResponse, _a1 error) *MockCourseService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCourseService_Create_Call) RunAndReturn(run func(context.Context, dto.CreateCourseRequest) (dto.CourseResponse, error)) *MockCourseService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockCourseService) Delete(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCourseService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockCourseService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockCourseService_Expecter) Delete(ctx interface{}, id interface{}) *MockCourseService_Delete_Call {
	return &MockCourseService_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockCourseService_Delete_Call) Run(run func(ctx context.Context, id uint)) *MockCourseService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockCourseService_Delete_Call) Return(_a0 error) *MockCourseService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCourseService_Delete_Call) RunAndReturn(run func(context.Context, uint) error) *MockCourseService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockCourseService) GetByID(ctx context.Context, id uint) (dto.CourseResponse, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 dto.CourseResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (dto.CourseResponse, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) dto.CourseResponse); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(dto.CourseResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCourseService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockCourseService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockCourseService_Expecter) GetByID(ctx interface{}, id interface{}) *MockCourseService_GetByID_Call {
	return &MockCourseService_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockCourseService_GetByID_Call) Run(run func(ctx context.Context, id uint)) *MockCourseService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockCourseService_GetByID_Call) Return(_a0 dto.CourseResponse, _a1 error) *MockCourseService_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCourseService_GetByID_Call) RunAndReturn(run func(context.Context, uint) (dto.CourseResponse, error)) *MockCourseService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByIDWithChapters provides a mock function with given fields: ctx, id
func (_m *MockCourseService) GetByIDWithChapters(ctx context.Context, id uint) (dto.CourseResponse, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByIDWithChapters")
	}

	var r0 dto.CourseResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (dto.CourseResponse, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) dto.CourseResponse); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(dto.CourseResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCourseService_GetByIDWithChapters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByIDWithChapters'
type MockCourseService_GetByIDWithChapters_Call struct {
	*mock.Call
}

// GetByIDWithChapters is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockCourseService_Expecter) GetByIDWithChapters(ctx interface{}, id interface{}) *MockCourseService_GetByIDWithChapters_Call {
	return &MockCourseService_GetByIDWithChapters_Call{Call: _e.mock.On("GetByIDWithChapters", ctx, id)}
}

func (_c *MockCourseService_GetByIDWithChapters_Call) Run(run func(ctx context.Context, id uint)) *MockCourseService_GetByIDWithChapters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockCourseService_GetByIDWithChapters_Call) Return(_a0 dto.CourseResponse, _a1 error) *MockCourseService_GetByIDWithChapters_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCourseService_GetByIDWithChapters_Call) RunAndReturn(run func(context.Context, uint) (dto.CourseResponse, error)) *MockCourseService_GetByIDWithChapters_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx
func (_m *MockCourseService) List(ctx context.Context) ([]dto.CourseResponse, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []dto.CourseResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]dto.CourseResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []dto.CourseResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.CourseResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCourseService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockCourseService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockCourseService_Expecter) List(ctx interface{}) *MockCourseService_List_Call {
	return &MockCourseService_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockCourseService_List_Call) Run(run func(ctx context.Context)) *MockCourseService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockCourseService_List_Call) Return(_a0 []dto.CourseResponse, _a1 error) *MockCourseService_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCourseService_List_Call) RunAndReturn(run func(context.Context) ([]dto.CourseResponse, error)) *MockCourseService_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, req
func (_m *MockCourseService) Update(ctx context.Context, id uint, req dto.UpdateCourseRequest) (dto.CourseResponse, error) {
	ret := _m.Called(ctx, id, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 dto.CourseResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, dto.UpdateCourseRequest) (dto.CourseResponse, error)); ok {
		return rf(ctx, id, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, dto.UpdateCourseRequest) dto.CourseResponse); ok {
		r0 = rf(ctx, id, req)
	} else {
		r0 = ret.Get(0).(dto.CourseResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, dto.UpdateCourseRequest) error); ok {
		r1 = rf(ctx, id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCourseService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockCourseService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
//   - req dto.UpdateCourseRequest
func (_e *MockCourseService_Expecter) Update(ctx interface{}, id interface{}, req interface{}) *MockCourseService_Update_Call {
	return &MockCourseService_Update_Call{Call: _e.mock.On("Update", ctx, id, req)}
}

func (_c *MockCourseService_Update_Call) Run(run func(ctx context.Context, id uint, req dto.UpdateCourseRequest)) *MockCourseService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(dto.UpdateCourseRequest))
	})
	return _c
}

func (_c *MockCourseService_Update_Call) Return(_a0 dto.CourseResponse, _a1 error) *MockCourseService_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCourseService_Update_Call) RunAndReturn(run func(context.Context, uint, dto.UpdateCourseRequest) (dto.CourseResponse, error)) *MockCourseService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCourseService creates a new instance of MockCourseService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCourseService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCourseService {
	mock := &MockCourseService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
