// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/dias-web/lms-system/internal/dto"
	mock "github.com/stretchr/testify/mock"
)

// MockLessonService is an autogenerated mock type for the LessonService type
type MockLessonService struct {
	mock.Mock
}

type MockLessonService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLessonService) EXPECT() *MockLessonService_Expecter {
	return &MockLessonService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, req
func (_m *MockLessonService) Create(ctx context.Context, req dto.CreateLessonRequest) (dto.LessonResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 dto.LessonResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateLessonRequest) (dto.LessonResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateLessonRequest) dto.LessonResponse); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(dto.LessonResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.CreateLessonRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLessonService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockLessonService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - req dto.CreateLessonRequest
func (_e *MockLessonService_Expecter) Create(ctx interface{}, req interface{}) *MockLessonService_Create_Call {
	return &MockLessonService_Create_Call{Call: _e.mock.On("Create", ctx, req)}
}

func (_c *MockLessonService_Create_Call) Run(run func(ctx context.Context, req dto.CreateLessonRequest)) *MockLessonService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dto.CreateLessonRequest))
	})
	return _c
}

func (_c *MockLessonService_Create_Call) Return(_a0 dto.LessonResponse, _a1 error) *MockLessonService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLessonService_Create_Call) RunAndReturn(run func(context.Context, dto.CreateLessonRequest) (dto.LessonResponse, error)) *MockLessonService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockLessonService) Delete(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLessonService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockLessonService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockLessonService_Expecter) Delete(ctx interface{}, id interface{}) *MockLessonService_Delete_Call {
	return &MockLessonService_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockLessonService_Delete_Call) Run(run func(ctx context.Context, id uint)) *MockLessonService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockLessonService_Delete_Call) Return(_a0 error) *MockLessonService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLessonService_Delete_Call) RunAndReturn(run func(context.Context, uint) error) *MockLessonService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockLessonService) GetByID(ctx context.Context, id uint) (dto.LessonResponse, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 dto.LessonResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (dto.LessonResponse, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) dto.LessonResponse); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(dto.LessonResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLessonService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockLessonService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockLessonService_Expecter) GetByID(ctx interface{}, id interface{}) *MockLessonService_GetByID_Call {
	return &MockLessonService_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockLessonService_GetByID_Call) Run(run func(ctx context.Context, id uint)) *MockLessonService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockLessonService_GetByID_Call) Return(_a0 dto.LessonResponse, _a1 error) *MockLessonService_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLessonService_GetByID_Call) RunAndReturn(run func(context.Context, uint) (dto.LessonResponse, error)) *MockLessonService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByChapter provides a mock function with given fields: ctx, chapterID
func (_m *MockLessonService) ListByChapter(ctx context.Context, chapterID uint) ([]dto.LessonResponse, error) {
	ret := _m.Called(ctx, chapterID)

	if len(ret) == 0 {
		panic("no return value specified for ListByChapter")
	}

	var r0 []dto.LessonResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]dto.LessonResponse, error)); ok {
		return rf(ctx, chapterID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []dto.LessonResponse); ok {
		r0 = rf(ctx, chapterID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.LessonResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, chapterID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLessonService_ListByChapter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByChapter'
type MockLessonService_ListByChapter_Call struct {
	*mock.Call
}

// ListByChapter is a helper method to define mock.On call
//   - ctx context.Context
//   - chapterID uint
func (_e *MockLessonService_Expecter) ListByChapter(ctx interface{}, chapterID interface{}) *MockLessonService_ListByChapter_Call {
	return &MockLessonService_ListByChapter_Call{Call: _e.mock.On("ListByChapter", ctx, chapterID)}
}

func (_c *MockLessonService_ListByChapter_Call) Run(run func(ctx context.Context, chapterID uint)) *MockLessonService_ListByChapter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockLessonService_ListByChapter_Call) Return(_a0 []dto.LessonResponse, _a1 error) *MockLessonService_ListByChapter_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLessonService_ListByChapter_Call) RunAndReturn(run func(context.Context, uint) ([]dto.LessonResponse, error)) *MockLessonService_ListByChapter_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, req
func (_m *MockLessonService) Update(ctx context.Context, id uint, req dto.UpdateLessonRequest) (dto.LessonResponse, error) {
	ret := _m.Called(ctx, id, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 dto.LessonResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, dto.UpdateLessonRequest) (dto.LessonResponse, error)); ok {
		return rf(ctx, id, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, dto.UpdateLessonRequest) dto.LessonResponse); ok {
		r0 = rf(ctx, id, req)
	} else {
		r0 = ret.Get(0).(dto.LessonResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, dto.UpdateLessonRequest) error); ok {
		r1 = rf(ctx, id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLessonService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockLessonService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
//   - req dto.UpdateLessonRequest
func (_e *MockLessonService_Expecter) Update(ctx interface{}, id interface{}, req interface{}) *MockLessonService_Update_Call {
	return &MockLessonService_Update_Call{Call: _e.mock.On("Update", ctx, id, req)}
}

func (_c *MockLessonService_Update_Call) Run(run func(ctx context.Context, id uint, req dto.UpdateLessonRequest)) *MockLessonService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(dto.UpdateLessonRequest))
	})
	return _c
}

func (_c *MockLessonService_Update_Call) Return(_a0 dto.LessonResponse, _a1 error) *MockLessonService_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLessonService_Update_Call) RunAndReturn(run func(context.Context, uint, dto.UpdateLessonRequest) (dto.LessonResponse, error)) *MockLessonService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLessonService creates a new instance of MockLessonService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLessonService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLessonService {
	mock := &MockLessonService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
