// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/dias-web/lms-system/internal/dto"
	mock "github.com/stretchr/testify/mock"
)

// MockAttachmentService is an autogenerated mock type for the AttachmentService type
type MockAttachmentService struct {
	mock.Mock
}

type MockAttachmentService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAttachmentService) EXPECT() *MockAttachmentService_Expecter {
	return &MockAttachmentService_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockAttachmentService) Delete(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAttachmentService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockAttachmentService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockAttachmentService_Expecter) Delete(ctx interface{}, id interface{}) *MockAttachmentService_Delete_Call {
	return &MockAttachmentService_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockAttachmentService_Delete_Call) Run(run func(ctx context.Context, id uint)) *MockAttachmentService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockAttachmentService_Delete_Call) Return(_a0 error) *MockAttachmentService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAttachmentService_Delete_Call) RunAndReturn(run func(context.Context, uint) error) *MockAttachmentService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Download provides a mock function with given fields: ctx, id
func (_m *MockAttachmentService) Download(ctx context.Context, id uint) (*dto.DownloadResult, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Download")
	}

	var r0 *dto.DownloadResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*dto.DownloadResult, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *dto.DownloadResult); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.DownloadResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAttachmentService_Download_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Download'
type MockAttachmentService_Download_Call struct {
	*mock.Call
}

// Download is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockAttachmentService_Expecter) Download(ctx interface{}, id interface{}) *MockAttachmentService_Download_Call {
	return &MockAttachmentService_Download_Call{Call: _e.mock.On("Download", ctx, id)}
}

func (_c *MockAttachmentService_Download_Call) Run(run func(ctx context.Context, id uint)) *MockAttachmentService_Download_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockAttachmentService_Download_Call) Return(_a0 *dto.DownloadResult, _a1 error) *MockAttachmentService_Download_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAttachmentService_Download_Call) RunAndReturn(run func(context.Context, uint) (*dto.DownloadResult, error)) *MockAttachmentService_Download_Call {
	_c.Call.Return(run)
	return _c
}

// ListByLesson provides a mock function with given fields: ctx, lessonID
func (_m *MockAttachmentService) ListByLesson(ctx context.Context, lessonID uint) ([]dto.AttachmentResponse, error) {
	ret := _m.Called(ctx, lessonID)

	if len(ret) == 0 {
		panic("no return value specified for ListByLesson")
	}

	var r0 []dto.AttachmentResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]dto.AttachmentResponse, error)); ok {
		return rf(ctx, lessonID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []dto.AttachmentResponse); ok {
		r0 = rf(ctx, lessonID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.AttachmentResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, lessonID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAttachmentService_ListByLesson_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByLesson'
type MockAttachmentService_ListByLesson_Call struct {
	*mock.Call
}

// ListByLesson is a helper method to define mock.On call
//   - ctx context.Context
//   - lessonID uint
func (_e *MockAttachmentService_Expecter) ListByLesson(ctx interface{}, lessonID interface{}) *MockAttachmentService_ListByLesson_Call {
	return &MockAttachmentService_ListByLesson_Call{Call: _e.mock.On("ListByLesson", ctx, lessonID)}
}

func (_c *MockAttachmentService_ListByLesson_Call) Run(run func(ctx context.Context, lessonID uint)) *MockAttachmentService_ListByLesson_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockAttachmentService_ListByLesson_Call) Return(_a0 []dto.AttachmentResponse, _a1 error) *MockAttachmentService_ListByLesson_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAttachmentService_ListByLesson_Call) RunAndReturn(run func(context.Context, uint) ([]dto.AttachmentResponse, error)) *MockAttachmentService_ListByLesson_Call {
	_c.Call.Return(run)
	return _c
}

// Upload provides a mock function with given fields: ctx, lessonID, in
func (_m *MockAttachmentService) Upload(ctx context.Context, lessonID uint, in dto.UploadInput) (dto.AttachmentResponse, error) {
	ret := _m.Called(ctx, lessonID, in)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 dto.AttachmentResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, dto.UploadInput) (dto.AttachmentResponse, error)); ok {
		return rf(ctx, lessonID, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, dto.UploadInput) dto.AttachmentResponse); ok {
		r0 = rf(ctx, lessonID, in)
	} else {
		r0 = ret.Get(0).(dto.AttachmentResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, dto.UploadInput) error); ok {
		r1 = rf(ctx, lessonID, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAttachmentService_Upload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upload'
type MockAttachmentService_Upload_Call struct {
	*mock.Call
}

// Upload is a helper method to define mock.On call
//   - ctx context.Context
//   - lessonID uint
//   - in dto.UploadInput
func (_e *MockAttachmentService_Expecter) Upload(ctx interface{}, lessonID interface{}, in interface{}) *MockAttachmentService_Upload_Call {
	return &MockAttachmentService_Upload_Call{Call: _e.mock.On("Upload", ctx, lessonID, in)}
}

func (_c *MockAttachmentService_Upload_Call) Run(run func(ctx context.Context, lessonID uint, in dto.UploadInput)) *MockAttachmentService_Upload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(dto.UploadInput))
	})
	return _c
}

func (_c *MockAttachmentService_Upload_Call) Return(_a0 dto.AttachmentResponse, _a1 error) *MockAttachmentService_Upload_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAttachmentService_Upload_Call) RunAndReturn(run func(context.Context, uint, dto.UploadInput) (dto.AttachmentResponse, error)) *MockAttachmentService_Upload_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAttachmentService creates a new instance of MockAttachmentService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAttachmentService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAttachmentService {
	mock := &MockAttachmentService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
