// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/dias-web/lms-system/internal/dto"
	mock "github.com/stretchr/testify/mock"
)

// MockChapterService is an autogenerated mock type for the ChapterService type
type MockChapterService struct {
	mock.Mock
}

type MockChapterService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChapterService) EXPECT() *MockChapterService_Expecter {
	return &MockChapterService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, req
func (_m *MockChapterService) Create(ctx context.Context, req dto.CreateChapterRequest) (dto.ChapterResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 dto.ChapterResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateChapterRequest) (dto.ChapterResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateChapterRequest) dto.ChapterResponse); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(dto.ChapterResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.CreateChapterRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockChapterService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockChapterService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - req dto.CreateChapterRequest
func (_e *MockChapterService_Expecter) Create(ctx interface{}, req interface{}) *MockChapterService_Create_Call {
	return &MockChapterService_Create_Call{Call: _e.mock.On("Create", ctx, req)}
}

func (_c *MockChapterService_Create_Call) Run(run func(ctx context.Context, req dto.CreateChapterRequest)) *MockChapterService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dto.CreateChapterRequest))
	})
	return _c
}

func (_c *MockChapterService_Create_Call) Return(_a0 dto.ChapterResponse, _a1 error) *MockChapterService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockChapterService_Create_Call) RunAndReturn(run func(context.Context, dto.CreateChapterRequest) (dto.ChapterResponse, error)) *MockChapterService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockChapterService) Delete(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockChapterService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockChapterService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockChapterService_Expecter) Delete(ctx interface{}, id interface{}) *MockChapterService_Delete_Call {
	return &MockChapterService_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockChapterService_Delete_Call) Run(run func(ctx context.Context, id uint)) *MockChapterService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockChapterService_Delete_Call) Return(_a0 error) *MockChapterService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChapterService_Delete_Call) RunAndReturn(run func(context.Context, uint) error) *MockChapterService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockChapterService) GetByID(ctx context.Context, id uint) (dto.ChapterResponse, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 dto.ChapterResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (dto.ChapterResponse, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) dto.ChapterResponse); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(dto.ChapterResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockChapterService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockChapterService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockChapterService_Expecter) GetByID(ctx interface{}, id interface{}) *MockChapterService_GetByID_Call {
	return &MockChapterService_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockChapterService_GetByID_Call) Run(run func(ctx context.Context, id uint)) *MockChapterService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockChapterService_GetByID_Call) Return(_a0 dto.ChapterResponse, _a1 error) *MockChapterService_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockChapterService_GetByID_Call) RunAndReturn(run func(context.Context, uint) (dto.ChapterResponse, error)) *MockChapterService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByIDWithLessons provides a mock function with given fields: ctx, id
func (_m *MockChapterService) GetByIDWithLessons(ctx context.Context, id uint) (dto.ChapterResponse, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByIDWithLessons")
	}

	var r0 dto.ChapterResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (dto.ChapterResponse, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) dto.ChapterResponse); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(dto.ChapterResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockChapterService_GetByIDWithLessons_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByIDWithLessons'
type MockChapterService_GetByIDWithLessons_Call struct {
	*mock.Call
}

// GetByIDWithLessons is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockChapterService_Expecter) GetByIDWithLessons(ctx interface{}, id interface{}) *MockChapterService_GetByIDWithLessons_Call {
	return &MockChapterService_GetByIDWithLessons_Call{Call: _e.mock.On("GetByIDWithLessons", ctx, id)}
}

func (_c *MockChapterService_GetByIDWithLessons_Call) Run(run func(ctx context.Context, id uint)) *MockChapterService_GetByIDWithLessons_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockChapterService_GetByIDWithLessons_Call) Return(_a0 dto.ChapterResponse, _a1 error) *MockChapterService_GetByIDWithLessons_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockChapterService_GetByIDWithLessons_Call) RunAndReturn(run func(context.Context, uint) (dto.ChapterResponse, error)) *MockChapterService_GetByIDWithLessons_Call {
	_c.Call.Return(run)
	return _c
}

// ListByCourse provides a mock function with given fields: ctx, courseID
func (_m *MockChapterService) ListByCourse(ctx context.Context, courseID uint) ([]dto.ChapterResponse, error) {
	ret := _m.Called(ctx, courseID)

	if len(ret) == 0 {
		panic("no return value specified for ListByCourse")
	}

	var r0 []dto.ChapterResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]dto.ChapterResponse, error)); ok {
		return rf(ctx, courseID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []dto.ChapterResponse); ok {
		r0 = rf(ctx, courseID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.ChapterResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, courseID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockChapterService_ListByCourse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByCourse'
type MockChapterService_ListByCourse_Call struct {
	*mock.Call
}

// ListByCourse is a helper method to define mock.On call
//   - ctx context.Context
//   - courseID uint
func (_e *MockChapterService_Expecter) ListByCourse(ctx interface{}, courseID interface{}) *MockChapterService_ListByCourse_Call {
	return &MockChapterService_ListByCourse_Call{Call: _e.mock.On("ListByCourse", ctx, courseID)}
}

func (_c *MockChapterService_ListByCourse_Call) Run(run func(ctx context.Context, courseID uint)) *MockChapterService_ListByCourse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockChapterService_ListByCourse_Call) Return(_a0 []dto.ChapterResponse, _a1 error) *MockChapterService_ListByCourse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockChapterService_ListByCourse_Call) RunAndReturn(run func(context.Context, uint) ([]dto.ChapterResponse, error)) *MockChapterService_ListByCourse_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, req
func (_m *MockChapterService) Update(ctx context.Context, id uint, req dto.UpdateChapterRequest) (dto.ChapterResponse, error) {
	ret := _m.Called(ctx, id, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 dto.ChapterResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, dto.UpdateChapterRequest) (dto.ChapterResponse, error)); ok {
		return rf(ctx, id, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, dto.UpdateChapterRequest) dto.ChapterResponse); ok {
		r0 = rf(ctx, id, req)
	} else {
		r0 = ret.Get(0).(dto.ChapterResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, dto.UpdateChapterRequest) error); ok {
		r1 = rf(ctx, id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockChapterService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockChapterService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
//   - req dto.UpdateChapterRequest
func (_e *MockChapterService_Expecter) Update(ctx interface{}, id interface{}, req interface{}) *MockChapterService_Update_Call {
	return &MockChapterService_Update_Call{Call: _e.mock.On("Update", ctx, id, req)}
}

func (_c *MockChapterService_Update_Call) Run(run func(ctx context.Context, id uint, req dto.UpdateChapterRequest)) *MockChapterService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(dto.UpdateChapterRequest))
	})
	return _c
}

func (_c *MockChapterService_Update_Call) Return(_a0 dto.ChapterResponse, _a1 error) *MockChapterService_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockChapterService_Update_Call) RunAndReturn(run func(context.Context, uint, dto.UpdateChapterRequest) (dto.ChapterResponse, error)) *MockChapterService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockChapterService creates a new instance of MockChapterService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChapterService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChapterService {
	mock := &MockChapterService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
