// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"

	storage "github.com/dias-web/lms-system/internal/storage"
)

// MockObjectStore is an autogenerated mock type for the ObjectStore type
type MockObjectStore struct {
	mock.Mock
}

type MockObjectStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockObjectStore) EXPECT() *MockObjectStore_Expecter {
	return &MockObjectStore_Expecter{mock: &_m.Mock}
}

// Download provides a mock function with given fields: ctx, key
func (_m *MockObjectStore) Download(ctx context.Context, key string) (*storage.Object, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Download")
	}

	var r0 *storage.Object
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*storage.Object, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *storage.Object); ok {
		r0 = rf(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*storage.Object)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockObjectStore_Download_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Download'
type MockObjectStore_Download_Call struct {
	*mock.Call
}

// Download is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockObjectStore_Expecter) Download(ctx interface{}, key interface{}) *MockObjectStore_Download_Call {
	return &MockObjectStore_Download_Call{Call: _e.mock.On("Download", ctx, key)}
}

func (_c *MockObjectStore_Download_Call) Run(run func(ctx context.Context, key string)) *MockObjectStore_Download_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockObjectStore_Download_Call) Return(_a0 *storage.Object, _a1 error) *MockObjectStore_Download_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockObjectStore_Download_Call) RunAndReturn(run func(context.Context, string) (*storage.Object, error)) *MockObjectStore_Download_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function with given fields: ctx, key
func (_m *MockObjectStore) Remove(ctx context.Context, key string) error {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockObjectStore_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type MockObjectStore_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockObjectStore_Expecter) Remove(ctx interface{}, key interface{}) *MockObjectStore_Remove_Call {
	return &MockObjectStore_Remove_Call{Call: _e.mock.On("Remove", ctx, key)}
}

func (_c *MockObjectStore_Remove_Call) Run(run func(ctx context.Context, key string)) *MockObjectStore_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockObjectStore_Remove_Call) Return(_a0 error) *MockObjectStore_Remove_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockObjectStore_Remove_Call) RunAndReturn(run func(context.Context, string) error) *MockObjectStore_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// Upload provides a mock function with given fields: ctx, key, r, size, contentType
func (_m *MockObjectStore) Upload(ctx context.Context, key string, r io.Reader, size int64, contentType string) error {
	ret := _m.Called(ctx, key, r, size, contentType)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader, int64, string) error); ok {
		r0 = rf(ctx, key, r, size, contentType)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockObjectStore_Upload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upload'
type MockObjectStore_Upload_Call struct {
	*mock.Call
}

// Upload is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - r io.Reader
//   - size int64
//   - contentType string
func (_e *MockObjectStore_Expecter) Upload(ctx interface{}, key interface{}, r interface{}, size interface{}, contentType interface{}) *MockObjectStore_Upload_Call {
	return &MockObjectStore_Upload_Call{Call: _e.mock.On("Upload", ctx, key, r, size, contentType)}
}

func (_c *MockObjectStore_Upload_Call) Run(run func(ctx context.Context, key string, r io.Reader, size int64, contentType string)) *MockObjectStore_Upload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(io.Reader), args[3].(int64), args[4].(string))
	})
	return _c
}

func (_c *MockObjectStore_Upload_Call) Return(_a0 error) *MockObjectStore_Upload_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockObjectStore_Upload_Call) RunAndReturn(run func(context.Context, string, io.Reader, int64, string) error) *MockObjectStore_Upload_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockObjectStore creates a new instance of MockObjectStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockObjectStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockObjectStore {
	mock := &MockObjectStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
