// Package main is the entry point for the LMS Main Service.
//
//	@title			LMS Main Service API
//	@version		1.0
//	@description	REST API for managing Courses, Chapters and Lessons in the LMS platform.
//	@description	All mutating endpoints (POST/PUT/DELETE) emit structured logs via logrus.
//	@description	Errors are returned in a unified shape: {"error":{"code":"...","message":"..."}}.
//	@host			localhost:8080
//	@BasePath		/
//	@schemes		http
//
//	@tag.name		health
//	@tag.description	Liveness probe.
//	@tag.name		courses
//	@tag.description	Top-level course catalog.
//	@tag.name		chapters
//	@tag.description	Chapters belong to a course.
//	@tag.name		lessons
//	@tag.description	Lessons belong to a chapter and carry the textual content.
package main

import (
	"context"
	"errors"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/dias-web/lms-system/internal/auth"
	"github.com/dias-web/lms-system/internal/config"
	"github.com/dias-web/lms-system/internal/handler"
	"github.com/dias-web/lms-system/internal/keycloak"
	"github.com/dias-web/lms-system/internal/middleware"
	"github.com/dias-web/lms-system/internal/repository"
	"github.com/dias-web/lms-system/internal/service"
	"github.com/dias-web/lms-system/pkg/database"
	"github.com/dias-web/lms-system/pkg/logger"
	"github.com/gin-gonic/gin"
	"github.com/pressly/goose/v3"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"

	_ "github.com/dias-web/lms-system/docs" // generated by `swag init`
)

func main() {
	cfg, err := config.Load()
	if err != nil {
		panic(err)
	}

	log := logger.New(cfg.App.Env, cfg.App.LogLevel)
	log.Infof("Starting LMS Main Service on port %s (env=%s, level=%s)",
		cfg.App.Port, cfg.App.Env, log.GetLevel())

	sqlDB, err := database.NewSQL(cfg.Postgres)
	if err != nil {
		log.Fatalf("connect postgres: %v", err)
	}
	defer sqlDB.Close()

	if err := goose.SetDialect("postgres"); err != nil {
		log.Fatalf("goose dialect: %v", err)
	}
	if err := goose.Up(sqlDB, "migrations"); err != nil {
		log.Fatalf("goose up: %v", err)
	}
	log.Info("Migrations applied successfully")

	gormDB, err := database.NewGorm(cfg.Postgres)
	if err != nil {
		log.Fatalf("gorm init: %v", err)
	}

	courseRepo := repository.NewCourseRepository(gormDB)
	chapterRepo := repository.NewChapterRepository(gormDB)
	lessonRepo := repository.NewLessonRepository(gormDB)

	courseSvc := service.NewCourseService(courseRepo, log)
	chapterSvc := service.NewChapterService(chapterRepo, courseRepo, log)
	lessonSvc := service.NewLessonService(lessonRepo, chapterRepo, log)

	if courses, err := courseSvc.List(context.Background()); err != nil {
		log.Warnf("smoke test: list courses failed: %v", err)
	} else {
		log.Infof("smoke test: %d course(s) found in database", len(courses))
		for _, c := range courses {
			log.Infof("  - [%d] %s", c.ID, c.Name)
		}
	}

	if cfg.App.Env == "production" {
		gin.SetMode(gin.ReleaseMode)
	}
	router := gin.New()
	router.HandleMethodNotAllowed = true
	router.Use(
		middleware.RequestLogger(log),
		middleware.Recovery(log),
		middleware.ErrorHandler(log),
	)
	router.NoRoute(middleware.NotFoundHandler())
	router.NoMethod(middleware.MethodNotAllowedHandler())

	router.GET("/health", handler.Health)

	// JWKS-backed validator; loads keys lazily on the first authenticated
	// request so the app can start before the Keycloak realm exists.
	validator := auth.NewValidator(cfg.Keycloak.CertsURL(), cfg.Keycloak.Issuer())
	authRequired := middleware.AuthRequired(validator, log)
	log.Infof("Auth enabled: validating JWTs issued by %s", cfg.Keycloak.Issuer())

	// Keycloak-backed authentication endpoints (login/refresh).
	kcClient := keycloak.NewClient(cfg.Keycloak)
	authSvc := service.NewAuthService(kcClient, log)
	handler.NewAuthHandler(authSvc).Register(router)

	// Mutations require a valid token; reads stay public.
	handler.NewCourseHandler(courseSvc).Register(router, authRequired)
	handler.NewChapterHandler(chapterSvc).Register(router, authRequired)
	handler.NewLessonHandler(lessonSvc).Register(router, authRequired)

	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	srv := &http.Server{
		Addr:              ":" + cfg.App.Port,
		Handler:           router,
		ReadHeaderTimeout: 10 * time.Second,
	}

	go func() {
		if err := srv.ListenAndServe(); err != nil && !errors.Is(err, http.ErrServerClosed) {
			log.Fatalf("listen: %v", err)
		}
	}()

	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)
	<-quit
	log.Info("Shutdown signal received")

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	if err := srv.Shutdown(ctx); err != nil {
		log.Errorf("server shutdown: %v", err)
	}
	log.Info("Server stopped")
}
